services:
  - type: web
    name: stars-gift-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: 8758203475:AAFQs5kgTLQFVCQAo5BxmovMaJ5079r5ntI
        sync: false          # You'll set this manually in Render dashboard
      - key: 8373846582
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
    healthCheckPath: /health
    autoDeploy: true
